// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqskpqqypzcbeexezfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcXNrcHFxeXB6Y2JlZXhlemZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjExMjAsImV4cCI6MjA3NTEzNzEyMH0.GC502Q9jmgAIMkHmXmytUWcbweK6OlPmF3EhdjsvEIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});